<a href="https://colab.research.google.com/github/19PA1A04B1/PYTHONBASICS/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
#numpy.arrange(start,stop,step)
import numpy as np
np.arange(10,15,1)

array([10, 11, 12, 13, 14])

In [14]:
#numpy.reshape(a,newshape)
#reshape means it gives the rows and columns...
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
#shape
import numpy as np
print(a.shape)

(3, 5)


In [18]:
#ndarray.ndim
#The number of axes (dimensions) of the array
print(a.ndim)

2


In [19]:
#a.dtype
#it gives the standard data type
print(a.dtype)

int64


In [21]:
# ndarray.size
#The total number of elements of the array.
#This is equal to the product of the elements of shape.(rors*columns)
print(a.size)

15


In [22]:
#type(ndarray)
print(type(a))

<class 'numpy.ndarray'>


In [23]:
np.zeros( (3,4) ) # creates an arrays of all zero(rows,columns)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones( (2,3), dtype=np.int16 ) 

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [25]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

print(A)
print(B)

print(A * B)  # elementwise product

print(A @ B)  # matrix product

print(A.dot(B)) # another matrix product

print(np.dot(A,B)) # another matrix product

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
