<a href="https://colab.research.google.com/github/19PA1A04B1/PYTHONBASICS/blob/master/Numpy_exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>**Numpy Introduction**</center>
![alt text](https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png)

Numpy is a general-purpose array-processing package...
It provides 
* High performance multi-dimensional arry object....
*   Tools to work with these array objects.....
* Numpy operations are vectorized..



It is mainly used in scientific computing....
-----
Importing numpy package....

In [0]:
import numpy as np



# **Creating 1-D array**
* We can create array using lists,tuples as follows

In [21]:
# create a numpy array using list
l=[1,2,3]
a=np.array(l)
print(a)





[1 2 3]


In [108]:
# create a numpy array from python tuple
a=np.array(((1,2,3),(4,5,6)))
print(tuple(tuple(a)))

(array([1, 2, 3]), array([4, 5, 6]))


* Python lists are similar to Numpy Lists...
* Then What is the purpose of having numpy arrays....
![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRADkTaMgXw0kSz05Rh7hAaoyGcik9UvBwqYAAVIB9uGJlFlXkJ)

* Because numpy arrays are faster and takes less memory...

In [22]:
# let's see a program to know the storage of numpy arrays...
import sys
l1=list(range(1000))
a3=np.array(l1)
print("Amount of memory consumed by python list..",len(l1)*sys.getsizeof(l1[0]))
print("Amount of memory consumed by numpy array...",a3.size*a3.itemsize)

Amount of memory consumed by python list.. 24000
Amount of memory consumed by numpy array... 8000


In [24]:
# let's see another program to know about time consumed by numpy arrays....
import time
t1=time.time()
for j in range(len(l1)):
  l1[j]+=5
t2=time.time()
a3=a3+5
t3=time.time()
print("Time taken by the list l1 to add 5 to each element of list is...",(t2-t1)*100000)
print("Time taken by the numpy array to add 5 to each element of numpy array is...",(t3-t2)*100000)

Time taken by the list l1 to add 5 to each element of list is... 25.963783264160156
Time taken by the numpy array to add 5 to each element of numpy array is... 123.09551239013672


* This is why we use numpy for scientific computing...

#### We can also create 2-D arrays.... 

* We can also create n-d arrays using python lists and tuples...

In [28]:
# create a 2-d array using list
a=np.array([[1,2,3],[4,5,6,]])
print(a)

[[1 2 3]
 [4 5 6]]


In [75]:
# we can also create n-d arrays with zeros using zeros method
a=np.zeros((2,2))
print(a)


[[0. 0.]
 [0. 0.]]


In [76]:
# we can also create n-d arrays with ones using ones method
a=np.eye(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
# create a 2-d array using tuples
a=np.array([(1,2,3),(4,5,6,)])
print(a)


[[1 2 3]
 [4 5 6]]


### Let's explore more about numpy arrays...

In [86]:
# let's see the datatype of numpy arrays....
a=np.array([(1.5,2.7,3.4),(4.1,5.2,6.3,)])
a.dtype



dtype('float64')

In [80]:
# shape or dimensions of numpy array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a.ndim)

(3, 3)
2


In [65]:
# size of numpy array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.size


9

In [102]:
# maximum element...
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.max())
print(a.argmax())


9
8


### Generating numbers between a range with a specific difference
- using function arange

In [92]:
# create an array of numbers using arange method
a=np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


### Generating **n** numbers between a range
- using function linspace

In [123]:
# use linspace method to create numpy array (start,end,no.of values)
np.linspace(0,1,10)



array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### Generating random sample of given dimensions
**Note - Random numbers are generated between 0 to 1. Multiply them with an appropriate factor to get required outcome.**

In [127]:
# creating numpy arrays of required dimensions with random numbers..
a=np.random.randn(2,3)
print(a)

[[ 1.43083928  1.17220549 -0.0884384 ]
 [ 0.11554511  0.35206529 -2.0206446 ]]


In [159]:
# What if we want to create an array with random numbers between 1 to 100
a=np.random.random([2,3])*100
print(a)

[[ 6.93569335 38.99733767 48.58039023]
 [33.88153759  2.64029968 25.76850332]]


### Basic array operations
**Note - The operations are vectorised**


In [177]:
# let's create two numpy arrays 
a=np.array([[1,2,3,4],[7,1,2,3]])
b=np.array([4,5,6,8])
print(a)
print(b)


[[1 2 3 4]
 [7 1 2 3]]
[4 5 6 8]


In [178]:
# we can do all arithmetic operations on numpy arrays with ease +,-,/,*,%
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[[ 5  7  9 12]
 [11  6  8 11]]
[[-3 -3 -3 -4]
 [ 3 -4 -4 -5]]
[[ 4 10 18 32]
 [28  5 12 24]]
[[0.25       0.4        0.5        0.5       ]
 [1.75       0.2        0.33333333 0.375     ]]
[[1 2 3 4]
 [3 1 2 3]]


In [179]:
# Broadcasting or recycling...
a=np.array([[1,2,3],[4,5,6]])
b=np.array([4,5,6,])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)





[[1 2 3]
 [4 5 6]]
[4 5 6]
[[ 5  7  9]
 [ 8 10 12]]
[[-3 -3 -3]
 [ 0  0  0]]
[[ 4 10 18]
 [16 25 36]]
[[0.25 0.4  0.5 ]
 [1.   1.   1.  ]]
[[1 2 3]
 [0 0 0]]


In [183]:
# Boolean operations
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[1]==2)
print(a[1]==5)

True
False


#### Matrix multiplication

In [195]:
# use matmul function
a=np.array([[1,2,3],[7,1,2]])
b=np.array([[4,5],[6,7],[8,9]])
print(np.matmul(a,b))




[[40 46]
 [50 60]]


### Some array operations
- max, min, sum, cumsum, sqrt, log etc

In [202]:
print(a.max(),a.min(),a.sum(),a.cumsum())


7 1 16 [ 1  3  6 13 14 16]


### Subsetting slicing and indexing
* We can access the elements of numpy n-d arrays using indexing..
* We can use numbers,array of numbers, boolean arrays as indices

In [208]:
#let's create a 2-d array..
a=np.array([[1,2,3],[7,1,2]])
print(a)
print(a[1)

[[1 2 3]
 [7 1 2]]
[]


In [0]:
# let's see boolean array indexing


In [0]:
# let's see the magic of boolean indexing...


In [0]:
# slicing


**Remember slices of numpy array shares memory..**

<centre> ![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTPd1SAx9N15GzpLNBp5gN_aAucYdFvj3ic9BpZVR48QW6qVOTu)
## ***yeah!***